import pygame
from pygame.locals import *
import random

VENTANA_HORIZONTAL = 800
VENTANA_VERTICAL = 600
MITAD_HORIZONTAL = int(VENTANA_HORIZONTAL / 2)
MITAD_VERTICAL = int(VENTANA_VERTICAL / 2)
FPS = 60
COLOR_FONDO = (0, 0, 0)
COLOR_TEXTO = (215, 20, 20)
COLOR_SNAKE = (215, 20, 20)
SIZE_SNAKE = 15
TITULO_JUEGO = "Mini-game Snake"
TEXTO_PAUSA = "Pausa"